### PR TITLE
fix #208: six-select not rendering (multiple, value = [null])

### LINKED ISSUE #208: six-select component doesn't support null value form multiple selections
### Six Webcomponents version

4.0.0

### Steps to reproduce

```
<div [formGroup]="filterForm">
     <six-select
        formControlName="status"
        id="status"
        multiple
        clearable
      >
        <six-menu-item value="AUSTRALIA">Australia</six-menu-item>
           <six-menu-item value="BRAZIL">Brazil</six-menu-item>
           <six-menu-item value="CHINA">China</six-menu-item>
      </six-select>
</div>
```

```
import { Component, OnInit} from '@angular/core';
import { FormBuilder, FormGroup} from '@angular/forms';

export class InitialComponent implements OnInit {
   public filterForm: FormGroup;

   constructor(private formBuilder: FormBuilder) {}

   ngOnInit(): void {
      this.filterForm = this.formBuilder.group({
            status: [null],
       });
    }
}
```

### What is expected?

No error on browser console

### What is actually happening?

An error in browser console. `Cannot read properties of null (reading 'length'). `

And browser doesn´t render the component.

### System Info

_No response_

### Any additional comments?

The app need to start six-select component with empty value as default. In old versions it worked with `value:[null]`. Now the way it works is with `value: [[]]`

### PR DESCRIPTION
**Pull request by davidemarcoli**
fix six-select not rendering when multiple is enabled and value is set to [null]

### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] It's submitted to the `main` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] I have updated the documentation accordingly.
- [x] All tests are passing
- [x] New/updated tests are included
- [x] I have updated the "upcoming" section inside _docs/changelog.md_ explaining the changes I contributed

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

**Review by colinscz — COMMENTED** [review]
- [x] Resolve conflict in changelog

File: libraries/ui-library/src/components/six-select/six-select.tsx [hunk 1]
```diff
@@ -743,7 +743,7 @@ export class SixSelect {
   }
 
   private hasSelection() {
-    return this.multiple ? this.value.length > 0 : this.value !== '';
+    return this.multiple ? this.value?.length > 0 : this.value !== '';
```
Comment (ibirrer) [inline libraries/ui-library/src/components/six-select/six-select.tsx:746]: Because `value` is typed as `@Prop({ mutable: true }) value: string | string[] = '';`, we should never need to do a check for `undefined`.

Instead of checking for a `null/undefined`  value, we should ensure it can never be `null` in the first place.

The check is actually already done [whenever the value changes](https://github.com/six-group/six-webcomponents/blob/main/libraries/ui-library/src/components/six-select/six-select.tsx#L191), but it seems to be missing when when the component is initially loaded.

Also see the info at https://stenciljs.com/docs/reactive-data#watch-decorator, that says "The @Watch() decorator does not fire when a component initially loads."

I guess we should check if other components are doing this correctly.

**Review by ibirrer — CHANGES_REQUESTED** [review]

File: libraries/ui-library/src/components/six-select/six-select.tsx (hunk 1 above)
Comment (davidemarcoli) [reply libraries/ui-library/src/components/six-select/six-select.tsx]: Now `handleValueChange` in called in the `componentWillLoad` lifecycle method. Other components (for example `six-input` also don't do this correctly)

**Review by ibirrer — CHANGES_REQUESTED** [review]

File: libraries/ui-library/src/components/six-select/six-select.tsx [hunk 2]
```diff
@@ -217,6 +217,7 @@ export class SixSelect {
   }
 
   componentWillLoad() {
+    this.handleValueChange();
```
[the remark this answers is not in the document]
Comment (ibirrer) [reply libraries/ui-library/src/components/six-select/six-select.tsx:213]: This can likely be changed to:
```ts
componentWillLoad() {
  this.value = convertToValidValue(this.value, this.multiple);
  this.handleSlotChange();
}
```

File: libraries/ui-library/src/components/six-select/six-select.tsx [hunk 3]
```diff
@@ -493,7 +479,7 @@ export class SixSelect {
       item.checked = value.includes(item.value);
     });
 
-    const checkedItems = getCheckedItems(this.getValueAsArray(), mainItems);
+    const checkedItems = getCheckedItems(Array.isArray(this.value) ? this.value : [this.value], mainItems);
```
Comment (ibirrer) [inline libraries/ui-library/src/components/six-select/six-select.tsx:482]: Might be worth to add another utility function to replace the two occurences of this expression:
```ts
export function convertToValidArrayValue(value: unknown): string[] {
  return convertToValidValue(value, true) as string[];
}
```

**Review by ibirrer — DISMISSED** [review]

**Review by ibirrer — APPROVED** [review]
