### PR TITLE
truncate large text in six-select and add tooltips fixes #67

### LINKED ISSUE #67: six-select with large items does not display the remove button and the additional entry count
### Six Webcomponents version

v4.0.0

### Steps to reproduce

1. Create a six-select with `multiple` enabled
2. Populate the six-select with multiple items that contain very long text (100+ characters)
3. Select multiple items
4. The text in the items will be cut off and the remove button is not displayed. Additionally the additional entry count is also not displayed

### What is expected?

- The remove button is always displayed, no matter the length of the item in the six-select
- The additional entry count is always displayed, no matter how many items are selected and no matter how long the text of the selected items is
- Optional: The text of very long items should be truncated (maybe show the full text in a tooltip on hover?)

### What is actually happening?

The text of the selected items will be cut off and the remove button is not displayed. Additionally the additional entry count is also not displayed

### System Info

```shell
System:                                                     
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz    
    Memory: 8.12 GB / 31.81 GB
  Binaries:
    Node: 16.19.0 - C:\develop\bin\node16\node.EXE
    npm: 8.19.3 - C:\develop\bin\node16\npm.CMD
  Browsers:
    Chrome: 115.0.5790.170
    Edge: Spartan (44.19041.1266.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.19041.1566
```

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by FabianKueng**
**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [x] It's submitted to the `main` branch for v2.x (or to a previous version branch)
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**
If the text exceeds the width of the `six-menu-item`, it is truncated. Additionally, a tooltip is shown for selected items in a `six-select` when `multiple` is set to true.

### CODE REVIEW

File: libraries/ui-library/src/components/six-select/six-select.tsx
Comment (ibirrer) [inline libraries/ui-library/src/components/six-select/six-select.tsx:1]: The left margin of the placeholder seems to have been lost with this change:
image

File: libraries/ui-library/src/components/six-select/six-select.tsx [hunk 1]
```diff
@@ -448,24 +448,26 @@ export class SixSelect {
...
-              event.stopPropagation();
-              if (!this.disabled) {
-                item.checked = false;
-                this.syncValueFromItems();
-              }
-            }}
-          >
-            {this.getItemLabel(item)}
-          </six-tag>
+          <six-tooltip content={item.textContent || ''}>
```
Comment (ibirrer) [inline libraries/ui-library/src/components/six-select/six-select.tsx:451]: Showing the tooltip even if none is needed could be a little cumbersome for the user. For example, the tooltip will always show, when the user wants to remove an item by clicking on the 'x'.

Better would be if the tooltip would only be showed for truncated item, but this might not be simple.

File: libraries/ui-library/src/components/six-select/six-select.tsx
Comment (FabianKueng) [reply libraries/ui-library/src/components/six-select/six-select.tsx:1]: Has been fixed, `getValueAsArray()` mistakenly converted an empty input value / empty string to an array with an empty string inside

File: libraries/ui-library/src/components/six-select/six-select.tsx (hunk 1 above)
Comment (FabianKueng) [reply libraries/ui-library/src/components/six-select/six-select.tsx]: Tooltip has been removed completely as we discussed earlier

**Review by ibirrer — APPROVED** [review]
