### PR TITLE
Prevent click event if button is disabled

### LINKED ISSUE #110: Button Component Emitting Click Event When Disabled
### Six Webcomponents version

4.0.2

### Steps to reproduce

- Create a button element with the disabled attribute set
- Add a click event listener to the button
- Trigger a click event on the button

### What is expected?

No event should be emitted when the button is clicked because it is disabled.

### What is actually happening?

The click event is emitted, and any associated event handlers are executed.

### System Info

_No response_

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by ibirrer**
Fixes #110

### CODE REVIEW

File: libraries/ui-library/src/components/six-button/six-button.tsx [hunk 1]
```diff
@@ -135,7 +135,7 @@ export class SixButton {
     const Button = isLink ? 'a' : 'button';
 
     return (
-      <div class={{ 'button-wrapper--disabled': this.disabled }}>
+      <div onClick={this.handleClick} class={{ 'button-wrapper--disabled': this.disabled }}>
```
Comment (Riatomerehentroweard) [inline libraries/ui-library/src/components/six-button/six-button.tsx:138]: would it be possible to add a unit test which catches this, i.e. makes sure no click is emitted for disabled button?

Comment (ibirrer) [reply libraries/ui-library/src/components/six-button/six-button.tsx:138]: Would be great, but I think we would need to add end-to-end tests for this, which we currently don't have.

**Review by huecking — APPROVED** [review]
