### PR TITLE
Fix #153: Show the correct active app in six-header

### LINKED ISSUE #153: Wrong app marked as selected in six-header
### Six Webcomponents version

4.0.4

### Steps to reproduce

- Add multiple `six-menu-item` elements to the `app-switcher-menu` slot of the `six-header`.
- Set `checked` to `false` on the first menu item and set it to `true` on one of the other items.
- The name of the first menu entry is used as the selected app in the header.

Additionally, if the list of menu items is updated after the initial render of the header (e.g., by loading available apps from the backend), the selected app does not update correctly.

### What is expected?

The selected app in the header should always correspond to the `six-menu-item` with the `checked` attribute set to `true`.

### What is actually happening?

1. The `six-header` only checks for the presence of the `checked` attribute and mistakenly considers a `six-menu-item` with `checked=false` as the selected app.
2. When the list of `six-menu-item` elements is dynamically updated, the `six-header` fails to update the selected app accordingly.

### System Info

_No response_

### Any additional comments?

_No response_

### PR DESCRIPTION
**Pull request by philippd**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation, readme or JSdoc annotations)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] 🧹 Chore (updates to the build process or auxiliary tools and libraries)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description
Fix for #153 

### 📝 Checklist

- [x] I have linked an issue or discussion.
- [x] It's submitted to the `main` branch
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [ ] I have updated the documentation accordingly.
- [x] All tests are passing
- [x] New/updated tests are included
- [x] I have updated the "upcoming" section inside _docs/changelog.md_ explaining the changes I contributed

If adding a **new feature**, the PR's description includes:

- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

File: libraries/ui-library/src/components/six-header/six-header.tsx [hunk 1]
```diff
@@ -194,27 +196,42 @@ export class SixHeader {
...
     }
 
     if (this.hasSlot(Slot.Search)) {
       this.computeSearchOpenState();
     }
   }
 
-  private getSelectedApp(): string | undefined {
+  componentDidLoad() {
+    const appSwitcherSlot = getSlot(this.host, Slot.AppSwitcher);
```
Comment (ibirrer) [inline libraries/ui-library/src/components/six-header/six-header.tsx:208]: It's probably better to initialize the mutation observer in the `connectedCallback` rather than in `componentDidLoad`. This is because once a component is disconnected, `componentDidLoad` won't be called again if the component reconnects. For more details, refer to the section on `connectedCallback` in the StencilJS Component Lifecycle documentation: https://stenciljs.com/docs/component-lifecycle#connectedcallback

**Review by ibirrer — CHANGES_REQUESTED** [review]

File: libraries/ui-library/src/components/six-header/six-header.tsx (hunk 1 above)
Comment (philippd) [reply libraries/ui-library/src/components/six-header/six-header.tsx:208]: makes sense, i changed this 👍 
i thought about changing it in `six-tab-group` too, but there is a lot more initialization going on in `componentDidLoad` and i did not want to risk introducing new bugs through this fix ;)

**Review by ibirrer — APPROVED** [review]
